#spring:
#  application:
#    name: spring-gateway


server:
    port: 8080

spring:
  application:
    name: spring-gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Ribbon을 사용하지 않도록 설정
    gateway:
      discovery:
        locator:
          enabled: true # Eureka를 통해 동적으로 서비스 목록을 가져올 수 있도록 설정
          lower-case-service-id: true
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/room/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: vote-service
          uri: lb://vote-service
          predicates:
            - Path=/vote/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
eureka:
  client:
    defaultZone: http://localhost:8761/eureka/ # Eureka 서버의 주소를 설정

auth:
  service:
    url: http://localhost:8084
service:
  room: http://localhost:8081
  user: http://localhost:8082
  vote: http://localhost:8083
  auth: http://localhost:8084