spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenCheck
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
          filters:
            - StripPrefix=1
        - id: vote-service
          uri: lb://VOTE-SERVICE
          predicates:
            - Path=/vote/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: sse-service
          uri: lb://SSE-SERVICE
          predicates:
            - Path=/sse/**
          filters:
            - StripPrefix=1
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka